### ISSUE TITLE
TF2 Bot detector URL is outdated

### ISSUE THREAD

**Issue by Ten0** [leighmacdonald/bd#76]
https://github.com/leighmacdonald/bd/blob/4675df3bb73f51bc679298e3bce991293a69e07a/README.md?plain=1#L9

still mentions the original `PazerOP` repo, but this has been forked and is now maintained here: https://github.com/surepy/tf2_bot_detector

I understand that it's easier for people to hack on a Go project than on an old c++ project, but just want to make sure that the two projects are aware of each other's existence and appropriately refer to each other so that they can collaborate as well as possible :)

**Comment by Barmem** [comment]
.py's fork is not endorsed considering py's reputation.

**Comment by Ten0** [comment]
What is that reputation?

**Comment by Barmem** [comment]
Cheating and contributing to cathook

**Comment by Ten0** [comment]
Thanks, noted. Not super clear to me how to use this one instead though, or if it's even going to be necessary to have it considering cathook seems to be dying just now. :)
Just as I get tired enough of bots to start looking for an actual solution, I realize they are just dying literally today ^^
